name: Prepare Release

on:
  workflow_dispatch:
  push:
    branches: ['main']
    paths: ['include/**', 'def/**']

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Prepare Release
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Set up ghauth config (Ubuntu)
        run: |
          mkdir -p ~/.config/changelog-maker/
          echo '{"user": "github-actions[bot]", "token": "'${{ secrets.GITHUB_TOKEN }}'"}' > ~/.config/changelog-maker/config.json
      - name: Update package version
        run: npm version --no-git-tag-version minor
      - name: Update changelog
        run: npm run --silent update-changelog
      - shell: bash
        id: pr-vars
        name: Compute Pull Request Variables
        run: |
          VERSION=$(jq -r ".version" package.json)
          COMMIT_MESSAGE="release: v$VERSION"
          BRANCH_NAME="release/v$VERSION"
          echo $COMMIT_MESSAGE
          if git ls-remote --exit-code --heads $GITHUB_SERVER_URL/$GITHUB_REPOSITORY $BRANCH_NAME >/dev/null; then
              echo "Branch exists. Nothing to do."
          else
            echo "Branch does not exists."
            echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_OUTPUT
            echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_OUTPUT
            echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          fi
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@6d6857d36972b65feb161a90e484f2984215f83e # v6.0.5
        if: ${{ steps.pr-vars.outputs.BRANCH_NAME }}
        with:
          branch: ${{ steps.pr-vars.outputs.BRANCH_NAME }}
          commit-message: ${{ steps.pr-vars.outputs.COMMIT_MESSAGE }}
          title: ${{ steps.pr-vars.outputs.COMMIT_MESSAGE }}
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          body: Automated release for version v${{ steps.pr-vars.outputs.VERSION }}
          labels: release
          delete-branch: true
