name: Publish Release

on:
  workflow_dispatch:
  push:
    branches: ['main']
    paths: ['package.json']

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Publish Release
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - shell: bash
        id: release-vars
        name: Compute Release Variables
        run: |
          VERSION=$(jq -r ".version" package.json)
          PACKAGE_NAME=$(jq -r ".name" package.json)
          npm show $PACKAGE_NAME@$VERSION && true
          SHOULD_PUBLISH_VERSION="$?"
          echo "VERSION=$VERSION PACKAGE_NAME=$PACKAGE_NAME SHOULD_PUBLISH_VERSION=$SHOULD_PUBLISH_VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "SHOULD_PUBLISH_VERSION=$SHOULD_PUBLISH_VERSION" >> $GITHUB_OUTPUT
      - name: Publish to npm
        if: ${{ steps.release-vars.outputs.SHOULD_PUBLISH_VERSION != '0' }}
        run:
          echo npm publish
      - name: Create GitHub Release
        if: ${{ steps.release-vars.outputs.SHOULD_PUBLISH_VERSION != '0' }}
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ steps.release-vars.outputs.VERSION }}
          commit: main
          name: Release ${{ steps.release-vars.outputs.VERSION }}
          generateReleaseNotes: true
          token: ${{ secrets.GITHUB_TOKEN }}
          skipIfReleaseExists: true
